uavcan_node_id:           41
uavcan_node_name:         "inno.actuators"
bridges:                  ["ActuatorsUavcanToRos",              "/uav/actuators_raw",
                           "ArmUavcanToRos",                    "/uav/arm"
]
